title: elmurod.net
description: software engineer's notes

url: https://elmurod.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate

paginate: 5

navigation:
  - title: Home
    url: /index.html
    icon: fa-home
  - title: About
    url: /about
    icon: fa-user
#  - title: Blog
#    url: /posts
#    icon: fa-bookmark

social:
  github: smartnode
  twitter: vorsagref
  linkedin: elmurod-talipov-0a730460
  email: elmurod.talipov@gmail.com

google_analytics: "UA-24495574-1"

show_drafts: false
future: false
